<a href="https://colab.research.google.com/github/Arpit-Sagar/AI-Prediction-Model/blob/main/08_02_2023_gpuCuda_programs_102003130.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

01/02/2023

In [ ]:
%load_ext nvcc_plugin

created output directory at /content/src
Out bin /content/result.out


In [ ]:
!nvidia-smi

Wed Apr 26 06:07:56 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   35C    P8     8W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [ ]:
!nvidia-smi -L

GPU 0: Tesla T4 (UUID: GPU-494c9330-a931-947e-a5fc-8578ad716ffc)


In [ ]:
!nvidia-smi -q


==============NVSMI LOG==============

Timestamp                                 : Wed Feb 22 10:40:46 2023
Driver Version                            : 510.47.03
CUDA Version                              : 11.6

Attached GPUs                             : 1
GPU 00000000:00:04.0
    Product Name                          : Tesla T4
    Product Brand                         : NVIDIA
    Product Architecture                  : Turing
    Display Mode                          : Enabled
    Display Active                        : Disabled
    Persistence Mode                      : Disabled
    MIG Mode
        Current                           : N/A
        Pending                           : N/A
    Accounting Mode                       : Disabled
    Accounting Mode Buffer Size           : 4000
    Driver Model
        Current                           : N/A
        Pending                           : N/A
    Serial Number                         : 1561121019005
    GPU UUID             

In [ ]:
!lscpu |grep 'Model name'

Model name:                      Intel(R) Xeon(R) CPU @ 2.20GHz


In [ ]:
%cd /usr/local


/usr/local


In [ ]:
!ls

bin    cuda-11	  games		      lib	 sbin	xgboost
colab  cuda-11.6  _gcs_config_ops.so  licensing  share
cuda   etc	  include	      man	 src


In [ ]:
%cd cuda


/usr/local/cuda-11.6


In [ ]:
!ls

bin		   DOCS      include	       nvml	share	 version.json
compat		   EULA.txt  lib64	       nvvm	src
compute-sanitizer  extras    libnvvp	       README	targets
doc		   gds	     nsightee_plugins  samples	tools


In [ ]:
%cd samples

/usr/local/cuda-11.6/samples


In [ ]:
!ls

README_CUDA_Samples.txt


In [ ]:
%cd 1_Utilities

[Errno 2] No such file or directory: '1_Utilities'
/usr/local/cuda-11.6/samples


In [ ]:
!ls

README_CUDA_Samples.txt


In [ ]:
%cd deviceQuery

[Errno 2] No such file or directory: 'deviceQuery'
/usr/local/cuda-11.6/samples


In [ ]:
!ls
!make

README_CUDA_Samples.txt
make: *** No targets specified and no makefile found.  Stop.


In [ ]:
!./deviceQuery

/bin/bash: ./deviceQuery: No such file or directory


In [ ]:
!nvcc --version

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Wed_Sep_21_10:33:58_PDT_2022
Cuda compilation tools, release 11.8, V11.8.89
Build cuda_11.8.r11.8/compiler.31833905_0


In [ ]:
!pip install git+https://github.com/andreinechaev/nvcc4jupyter.git

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
  Cloning https://github.com/andreinechaev/nvcc4jupyter.git to /tmp/pip-req-build-5_g1uuic
  Running command git clone --filter=blob:none --quiet https://github.com/andreinechaev/nvcc4jupyter.git /tmp/pip-req-build-5_g1uuic
  Resolved https://github.com/andreinechaev/nvcc4jupyter.git to commit aac710a35f52bb78ab34d2e52517237941399eff
  Preparing metadata (setup.py) ... done
  Created wheel for NVCCPlugin: filename=NVCCPlugin-0.0.2-py3-none-any.whl size=4305 sha256=5ccb96b510586eded28b982360677e085c4ed72d5cf139a329bb666a546cdc7e
  Stored in directory: /tmp/pip-ephem-wheel-cache-kvirakmo/wheels/db/c1/1f/a2bb07bbb4a1ce3c43921252aeafaa6205f08637e292496f04
Successfully built NVCCPlugin


In [ ]:
%%cu
#include <iostream>
	int
	main()
{
	std::cout << "Welcome \n";
	return 0;
}


Welcome 



In [ ]:
import numpy as np
import pandas as pd
arr=np.random.randint(10,size=(9,9))
print(arr)
#np.savetxt('data.csv',arr,delimiter=',')
pd.DataFrame(arr).to_csv('sample.csv')

[[1 3 1 6 3 2 5 3 9]
 [7 1 3 5 2 2 5 3 1]
 [4 2 6 6 2 9 3 6 0]
 [3 1 7 7 9 8 7 1 1]
 [3 5 4 4 9 3 1 4 2]
 [6 0 6 4 6 7 9 4 3]
 [5 5 8 4 5 0 5 2 3]
 [6 1 0 1 3 5 7 1 6]
 [1 1 7 1 0 5 2 5 1]]


In [ ]:
pip install numba


Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
pip install cudatoolkit

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
ERROR: Could not find a version that satisfies the requirement cudatoolkit (from versions: none)
ERROR: No matching distribution found for cudatoolkit


In [ ]:
from numba import jit, cuda
import numpy as np
# to measure exec time
from timeit import default_timer as timer

# normal function to run on cpu
def func(a):
	for i in range(10000000):
		a[i]+= 1

# function optimized to run on gpu
@jit(target_backend='cuda')
def func2(a):
	for i in range(10000000):
		a[i]+= 1
if __name__=="__main__":
	n = 10000000
	a = np.ones(n, dtype = np.float64)

	start = timer()
	func(a)
	print("without GPU:", timer()-start)

	start = timer()
	func2(a)
	print("with GPU:", timer()-start)


without GPU: 4.597418445000017
with GPU: 0.09698830800004998


In [ ]:
from numba import jit, cuda
import numpy as np
import pandas as pd

# to measure exec time
from timeit import default_timer as timer



@jit(target_backend='cuda')


def func():
  df=pd.read_csv('sample.csv')
  print(df)

if __name__=="__main__":
  start = timer()
  func()
  print("with GPU:",timer()-start)

   Unnamed: 0  0  1  2  3  4  5  6  7  8
0           0  1  3  1  6  3  2  5  3  9
1           1  7  1  3  5  2  2  5  3  1
2           2  4  2  6  6  2  9  3  6  0
3           3  3  1  7  7  9  8  7  1  1
4           4  3  5  4  4  9  3  1  4  2
5           5  6  0  6  4  6  7  9  4  3
6           6  5  5  8  4  5  0  5  2  3
7           7  6  1  0  1  3  5  7  1  6
8           8  1  1  7  1  0  5  2  5  1
with GPU: 0.14459092000004148


<ipython-input-13-20a8c39aa7fc>:10: NumbaWarning: 
Compilation is falling back to object mode WITH looplifting enabled because Function "func" failed type inference due to: Unknown attribute 'read_csv' of type Module(<module 'pandas' from '/usr/local/lib/python3.8/dist-packages/pandas/__init__.py'>)

File "<ipython-input-13-20a8c39aa7fc>", line 14:
def func():
  df=pd.read_csv('sample.csv')
  ^

During: typing of get attribute at <ipython-input-13-20a8c39aa7fc> (14)

File "<ipython-input-13-20a8c39aa7fc>", line 14:
def func():
  df=pd.read_csv('sample.csv')
  ^

  @jit(target_backend='cuda')
/usr/local/lib/python3.8/dist-packages/numba/core/object_mode_passes.py:151: NumbaWarning: Function "func" was compiled in object mode without forceobj=True.

File "<ipython-input-13-20a8c39aa7fc>", line 13:

def func():
^

  warnings.warn(errors.NumbaWarning(warn_msg,
/usr/local/lib/python3.8/dist-packages/numba/core/object_mode_passes.py:161: NumbaDeprecationWarning: 
Fall-back from the nopython 

In [ ]:
%%cu
import pandas as pd
import numpy as np
df=pd.read_csv('sample.csv')
df

/tmp/tmpz6hcbk8i/5a9bbdc7-ed37-4325-a27b-4848757f03b2.cu(1): error: identifier "import" is undefined

/tmp/tmpz6hcbk8i/5a9bbdc7-ed37-4325-a27b-4848757f03b2.cu(1): error: expected a ";"

/tmp/tmpz6hcbk8i/5a9bbdc7-ed37-4325-a27b-4848757f03b2.cu(3): warning #1654-D: too many characters in character literal -- extra leading characters ignored

2 errors detected in the compilation of "/tmp/tmpz6hcbk8i/5a9bbdc7-ed37-4325-a27b-4848757f03b2.cu".



In [ ]:
%%cu
#include<stdio.h>
#include<cuda.h>

__global__ void arradd(int *x,int *y, int *z)    //kernel definition
{
  int id=blockIdx.x;
/* blockIdx.x gives the respective block id which starts from 0 */
  z[id]=x[id]+y[id];
}

int main()
{
    int a[6];
    int b[6];
    int c[6];
    int *d,*e,*f;
    int i;
    printf("\n Enter six elements of first array\n");
    for(i=0;i<6;i++)
    {
        scanf("%d",&a[i]);
    }
    printf("\n Enter six elements of second array\n");
        for(i=0;i<6;i++)
        {
            scanf("%d",&b[i]);
        }

/* cudaMalloc() allocates memory from Global memory on GPU */
    cudaMalloc((void **)&d,6*sizeof(int));
    cudaMalloc((void **)&e,6*sizeof(int));
    cudaMalloc((void **)&f,6*sizeof(int));

/* cudaMemcpy() copies the contents from destination to source. Here destination is GPU(d,e) and source is CPU(a,b) */
 cudaMemcpy(d,a,6*sizeof(int),cudaMemcpyHostToDevice);
 cudaMemcpy(e,b,6*sizeof(int),cudaMemcpyHostToDevice);

/* call to kernel. Here 6 is number of blocks, 1 is the number of threads per block and d,e,f are the arguments */
arradd<<<6,1>>>(d,e,f);

/* Here we are copying content from GPU(Device) to CPU(Host) */
 cudaMemcpy(c,f,6*sizeof(int),cudaMemcpyDeviceToHost);

printf("\nSum of two arrays:\n ");
    for(i=0;i<6;i++)
    {
        printf("%d\t",c[i]);
    }

/* Free the memory allocated to pointers d,e,f */
    cudaFree(d);
    cudaFree(e);
    cudaFree(f);

    return 0;
}


 Enter six elements of first array

 Enter six elements of second array

Sum of two arrays:
 1901748788	32766	-1010437622	43778	-1434861848	32662	


In [ ]:
%%cu
#include <stdio.h>
#include <stdlib.h>


#include <cuda_runtime.h>

#define THREADS_PER_BLOCK 1024

__global__ void mergeSort(int *arr, int *temp, int n) {
    int tid = blockIdx.x * blockDim.x + threadIdx.x;
    int left = tid * 2;
    int right = tid * 2 + 1;
    int mid = (left + right) / 2;

    if (left < n && right < n) {
        mergeSort<<<1,1>>>(arr, temp, left);
        mergeSort<<<1,1>>>(arr, temp, right);
        cudaDeviceSynchronize();
        int i = left, j = mid, k = 0;
        while (i < mid && j < right) {
            if (arr[i] < arr[j]) {
                temp[k++] = arr[i++];
            } else {
                temp[k++] = arr[j++];
            }
        }
        while (i < mid) {
            temp[k++] = arr[i++];
        }
        while (j < right) {
            temp[k++] = arr[j++];
        }
        for (i = 0; i < k; i++) {
            arr[left + i] = temp[i];
        }
    }
}

int main() {
    int n = 1024;
    int *arr = (int *)malloc(n * sizeof(int));
    int *temp = (int *)malloc(n * sizeof(int));
    int *d_arr, *d_temp;

    cudaMalloc(&d_arr, n * sizeof(int));
    cudaMalloc(&d_temp, n * sizeof(int));

    for (int i = 0; i < n; i++) {
        arr[i] = rand() % n;
    }

    cudaMemcpy(d_arr, arr, n * sizeof(int), cudaMemcpyHostToDevice);
    cudaMemcpy(d_temp, temp, n * sizeof(int), cudaMemcpyHostToDevice);

    mergeSort<<<n / THREADS_PER_BLOCK, THREADS_PER_BLOCK>>>(d_arr, d_temp, n);
    cudaDeviceSynchronize();

    cudaMemcpy(arr, d_arr, n * sizeof(int), cudaMemcpyDeviceToHost);

    for (int i = 0; i < n; i++) {
        printf("%d ", arr[i]);
    }
    printf("\n");

    free(arr);
    free(temp);
    cudaFree(d_arr);
    cudaFree(d_temp);

    return 0;
}


/tmp/tmpzexkwyll/e261e109-a250-4fb5-9ae2-7d223d0f30ca.cu(16): error: kernel launch from __device__ or __global__ functions requires separate compilation mode

/tmp/tmpzexkwyll/e261e109-a250-4fb5-9ae2-7d223d0f30ca.cu(17): error: kernel launch from __device__ or __global__ functions requires separate compilation mode

/tmp/tmpzexkwyll/e261e109-a250-4fb5-9ae2-7d223d0f30ca.cu(18): warning #1444-D: function "cudaDeviceSynchronize"
/usr/local/cuda/bin/../targets/x86_64-linux/include/cuda_device_runtime_api.h(139): here was declared deprecated ("Use of cudaDeviceSynchronize from device code is deprecated. Moreover, such use will cause this module to fail to load on sm_90+ devices. If calls to cudaDeviceSynchronize from device code cannot be removed for older devices at this time, you may guard them with __CUDA_ARCH__ macros to remove them only for sm_90+ devices, making sure to generate code for compute_90 for the macros to take effect. Note that this mitigation will no longer work when suppo

In [ ]:
%%cu
#include <cstdio>
#include <iostream>

	using namespace std;

__global__ void maxi(int* a, int* b, int n)
{
	int block = 256 * blockIdx.x;
	int max = 0;

	for (int i = block; i < min(256 + block, n); i++) {

		if (max < a[i]) {
			max = a[i];
		}
	}
	b[blockIdx.x] = max;
}

int main()
{

	int n;
	n = 3 >> 2;
	int a[n];

	for (int i = 0; i < n; i++) {
		a[i] = rand() % n;
		cout << a[i] << "\t";
	}

	cudaEvent_t start, end;
	int *ad, *bd;
	int size = n * sizeof(int);
	cudaMalloc(&ad, size);
	cudaMemcpy(ad, a, size, cudaMemcpyHostToDevice);
	int grids = ceil(n * 1.0f / 256.0f);
	cudaMalloc(&bd, grids * sizeof(int));

	dim3 grid(grids, 1);
	dim3 block(1, 1);

	cudaEventCreate(&start);
	cudaEventCreate(&end);
	cudaEventRecord(start);

	while (n > 1) {
		maxi<<<grids, block>>>(ad, bd, n);
		n = ceil(n * 1.0f / 256.0f);
		cudaMemcpy(ad, bd, n * sizeof(int), cudaMemcpyDeviceToDevice);
	}

	cudaEventRecord(end);
	cudaEventSynchronize(end);

	float time = 0;
	cudaEventElapsedTime(&time, start, end);

	int ans[2];
	cudaMemcpy(ans, ad, 4, cudaMemcpyDeviceToHost);

	cout << "The maximum element is : " << ans[0] << endl;

	cout << "The time required : ";
	cout << time << endl;
}

The maximum element is : 0
The time required : 0.004096



In [ ]:
%%cu
#include<cuda.h>
#include<stdio.h>


 __global__ void cuda_hello()
  {
    printf("Hello World from my GPU :\n");
  }
 int main()
 {
    cuda_hello<<<5,2>>>();
    cudaDeviceSynchronize();
    return 0;
 }

Hello World from my GPU :
Hello World from my GPU :
Hello World from my GPU :
Hello World from my GPU :
Hello World from my GPU :
Hello World from my GPU :
Hello World from my GPU :
Hello World from my GPU :
Hello World from my GPU :
Hello World from my GPU :



In [ ]:
%%cu
#include <iostream>
#include "cuda_runtime.h"
#include "device_launch_parameters.h"
#include <curand_kernel.h>
#include <ctime>

__global__ void cudaRand(double *d_out)
{
    int i = blockDim.x * blockIdx.x + threadIdx.x;
    curandState state;
    curand_init((unsigned long long)clock() + i, 0, 0, &state);

    d_out[i] = curand_uniform_double(&state);
}

int main(int argc, char** argv)
{
    size_t N = 1 << 4;
    double *h_v = new double[N];

    double *d_out;
    cudaMalloc((void**)&d_out, N * sizeof(double));

    // generate random numbers
    cudaRand << < 1, N >> > (d_out);

    cudaMemcpy(h_v, d_out, N * sizeof(double), cudaMemcpyDeviceToHost);

    for (size_t i = 0; i < N; i++)
        printf("out: %f\n", h_v[i]);

    cudaFree(d_out);
    delete[] h_v;

    return 0;
}

out: 0.413244
out: 0.140371
out: 0.717849
out: 0.031107
out: 0.410113
out: 0.047287
out: 0.202498
out: 0.092819
out: 0.965160
out: 0.807151
out: 0.842902
out: 0.562337
out: 0.563488
out: 0.265575
out: 0.108357
out: 0.232280



In [ ]:
%%cu
#include <iostream>
#include "cuda_runtime.h"
#include "device_launch_parameters.h"
#include <curand_kernel.h>
#include <ctime>

__global__ void cudaRand(double *d_out)
{
    int i = blockDim.x * blockIdx.x + threadIdx.x;
    curandState state;
    curand_init((unsigned long long)clock() + i, 0, 0, &state);

    d_out[i] = curand_uniform_double(&state);
}

int main(int argc, char** argv)
{
    size_t N = 1 << 4;
    double *h_v = new double[N];

    double *d_out;
    cudaMalloc((void**)&d_out, N * sizeof(double));

    // generate random numbers
    cudaRand << < N, 1 >> > (d_out);

    cudaMemcpy(h_v, d_out, N * sizeof(double), cudaMemcpyDeviceToHost);

    for (size_t i = 0; i < N; i++)
        printf("out: %f\n", h_v[i]);

    cudaFree(d_out);
    delete[] h_v;

    return 0;
}

out: 0.548421
out: 0.550300
out: 0.516128
out: 0.519775
out: 0.909517
out: 0.848495
out: 0.882802
out: 0.426765
out: 0.954312
out: 0.970887
out: 0.026150
out: 0.235812
out: 0.702882
out: 0.123752
out: 0.509591
out: 0.968248



In [ ]:
%%cu
#include <iostream>
#include "cuda_runtime.h"
#include "device_launch_parameters.h"
#include <curand_kernel.h>
#include <ctime>

__global__ void cudaRand(double *d_out)
{
    int i = blockDim.x * blockIdx.x + threadIdx.x;
    curandState state;
    curand_init((unsigned long long)clock() + i, 0, 0, &state);

    d_out[i] = curand_uniform_double(&state);
}

int main(int argc, char** argv)
{
    size_t N = 1 << 4;
    double *h_v = new double[N];

    double *d_out;
    cudaMalloc((void**)&d_out, N * sizeof(double));

    // generate random numbers
    cudaRand << < N, N >> > (d_out);

    cudaMemcpy(h_v, d_out, N * sizeof(double), cudaMemcpyDeviceToHost);

    for (size_t i = 0; i < N; i++)
        printf("out: %f\n", h_v[i]);

    cudaFree(d_out);
    delete[] h_v;

    return 0;
}

out: 0.938532
out: 0.525846
out: 0.533323
out: 0.876369
out: 0.277741
out: 0.426509
out: 0.048946
out: 0.613472
out: 0.958278
out: 0.788139
out: 0.248142
out: 0.245766
out: 0.379118
out: 0.503720
out: 0.443981
out: 0.135484



In [ ]:
%%cu
//ADD two numbers using cuda
#include <iostream>
#include "cuda_runtime.h"
#include "device_launch_parameters.h"
#include <curand_kernel.h>
#include <ctime>
__global__ void add(int *a, int *b,int *c) //Kernel Definition
{
    *c = *a + *b;
    //printf(*a, *b, *c);
}
int main()
{
  int a, b, c; // host copies of a, b, c
  int *d_a, *d_b, *d_c; // device copies of a, b, c
  int size = sizeof(int);
  // Allocate space for device copies of a, b, c
  cudaMalloc((void **)&d_a, size);
  cudaMalloc((void **)&d_b, size);
  cudaMalloc((void **)&d_c, size);
  // Setup input values
  a = 2;
  b = 7;
  // Copy inputs to device
  cudaMemcpy(d_a, &a, size, cudaMemcpyHostToDevice);
  cudaMemcpy(d_b, &b, size, cudaMemcpyHostToDevice);
  // Launch add() kernel on GPU
   add<<<1,1>>>(d_a, d_b, d_c);
  // Copy result back to host
  cudaMemcpy(&c, d_c, size, cudaMemcpyDeviceToHost);
  printf("The answer is ");
  printf("%d",c);
  // Cleanup
  cudaFree(d_a); cudaFree(d_b); cudaFree(d_c);
  return 0;
}

The answer is 9


In [ ]:
%%cu

#include <stdio.h>
#include <stdlib.h>
#include<cuda.h>
#include <cuda_runtime.h>
#include <curand.h>
#include <curand_kernel.h>

#define CUDA_CALL(x) do { if((x)!=cudaSuccess) { \
    printf("Error at %s:%d\n",__FILE__,__LINE__);\
    return EXIT_FAILURE;}} while(0)
#define CURAND_CALL(x) do { if((x)!=CURAND_STATUS_SUCCESS) { \
    printf("Error at %s:%d\n",__FILE__,__LINE__);\
    return EXIT_FAILURE;}} while(0)

int main(int argc, char *argv[])
{
    size_t n = 100;
    size_t i;
    curandGenerator_t gen;
    float *devData, *hostData;

    /* Allocate n floats on host */
    hostData = (float *)calloc(n, sizeof(float));

    /* Allocate n floats on device */
    CUDA_CALL(cudaMalloc((void **)&devData, n*sizeof(float)));

    /* Create pseudo-random number generator */
    CURAND_CALL(curandCreateGenerator(&gen,
                CURAND_RNG_PSEUDO_DEFAULT));

    /* Set seed */
    CURAND_CALL(curandSetPseudoRandomGeneratorSeed(gen,
                1234ULL));

    /* Generate n floats on device */
    CURAND_CALL(curandGenerateUniform(gen, devData, n));

    /* Copy device memory to host */
    CUDA_CALL(cudaMemcpy(hostData, devData, n * sizeof(float),
        cudaMemcpyDeviceToHost));

    /* Show result */
    for(i = 0; i < n; i++) {
        printf("%1.4f ", hostData[i]);
    }
    printf("\n");

    /* Cleanup */
    CURAND_CALL(curandDestroyGenerator(gen));
    CUDA_CALL(cudaFree(devData));
    free(hostData);
    return EXIT_SUCCESS;
}

/usr/bin/ld: /tmp/tmpxft_0000043e_00000000-11_e063b70a-3d37-4ed6-8125-c79b5fc0346a.o: in function `main':
tmpxft_0000043e_00000000-6_e063b70a-3d37-4ed6-8125-c79b5fc0346a.cudafe1.cpp:(.text+0xb1): undefined reference to `curandCreateGenerator'
/usr/bin/ld: tmpxft_0000043e_00000000-6_e063b70a-3d37-4ed6-8125-c79b5fc0346a.cudafe1.cpp:(.text+0xf2): undefined reference to `curandSetPseudoRandomGeneratorSeed'
/usr/bin/ld: tmpxft_0000043e_00000000-6_e063b70a-3d37-4ed6-8125-c79b5fc0346a.cudafe1.cpp:(.text+0x139): undefined reference to `curandGenerateUniform'
/usr/bin/ld: tmpxft_0000043e_00000000-6_e063b70a-3d37-4ed6-8125-c79b5fc0346a.cudafe1.cpp:(.text+0x215): undefined reference to `curandDestroyGenerator'
collect2: error: ld returned 1 exit status



In [ ]:
%%cu
/*
* This program uses the host CURAND API to generate 100
* pseudorandom floats.
*/
#include <stdio.h>
#include <stdlib.h>
#include <cuda.h>
#include <curand.h>
#include <curand_kernel.h>
#define CUDA_CALL(x) do { if((x) != cudaSuccess)

printf("Error at %s:%d\n",__FILE__,__LINE__);
return EXIT_FAILURE;}} while(0)
#define CURAND_CALL(x) do { if((x) != CURAND_STATUS_SUCCESS) { \
printf("Error at %s:%d\n",__FILE__,__LINE__);\
return EXIT_FAILURE;}} while(0)
int main(int argc, char *argv[])
{
size_t n = 100;
size_t i;
curandGenerator_t gen;
float *devData, *hostData;
/* Allocate n floats on host */
hostData = (float *)calloc(n, sizeof(float));
/* Allocate n floats on device */
CUDA_CALL(cudaMalloc((void **)&devData, n * sizeof(float)));
/* Create pseudo-random number generator */
CURAND_CALL(curandCreateGenerator(&gen,
CURAND_RNG_PSEUDO_DEFAULT));
 /* Set seed */
CURAND_CALL(curandSetPseudoRandomGeneratorSeed(gen, 1234ULL));
/* Generate n floats on device */
CURAND_CALL(curandGenerateUniform(gen, devData, n));
/* Copy device memory to host */
CUDA_CALL(cudaMemcpy(hostData, devData, n * sizeof(float),
cudaMemcpyDeviceToHost));
/* Show result */
for(i = 0; i < n; i++) {
printf("%1.4f ", hostData[i]);
}
printf("\n");
/* Cleanup */
CURAND_CALL(curandDestroyGenerator(gen));
CUDA_CALL(cudaFree(devData));
free(hostData);
return EXIT_SUCCESS;
}

/tmp/tmpnpyia63i/5522c67b-b313-4031-81a3-53d62ff9b264.cu(12): error: this declaration has no storage class or type specifier

/tmp/tmpnpyia63i/5522c67b-b313-4031-81a3-53d62ff9b264.cu(12): error: declaration is incompatible with "int printf(const char *, ...)"
/usr/local/cuda/bin/../targets/x86_64-linux/include/crt/common_functions.h(153): here

/tmp/tmpnpyia63i/5522c67b-b313-4031-81a3-53d62ff9b264.cu(12): error: too many initializer values

/tmp/tmpnpyia63i/5522c67b-b313-4031-81a3-53d62ff9b264.cu(12): error: a value of type "const char *" cannot be used to initialize an entity of type "int"

/tmp/tmpnpyia63i/5522c67b-b313-4031-81a3-53d62ff9b264.cu(13): error: expected a declaration

/tmp/tmpnpyia63i/5522c67b-b313-4031-81a3-53d62ff9b264.cu(13): warning #12-D: parsing restarts here after previous syntax error

/tmp/tmpnpyia63i/5522c67b-b313-4031-81a3-53d62ff9b264.cu(13): error: expected a declaration

/tmp/tmpnpyia63i/5522c67b-b313-4031-81a3-53d62ff9b264.cu(31): warning #12-D: parsing re

In [ ]:
%%cu
#include<stdio.h>
#include<cuda.h>
#include<cuda_runtime_api.h>

__global__ void AddIntsCUDA(int *a, int *b,int *c) //Kernel Definition
{
    *c = *a + *b;
}

int main()
{
 int a = 5, b = 9;
 int c;
 int *d_a, *d_b, *d_c; //Device variable Declaration

        //Allocation of Device Variables
 cudaMalloc((void **)&d_a, sizeof(int));
 cudaMalloc((void **)&d_b, sizeof(int));
 cudaMalloc((void **)&d_c, sizeof(int));

        //Copy Host Memory to Device Memory
 cudaMemcpy(d_a, &a, sizeof(int), cudaMemcpyHostToDevice);
 cudaMemcpy(d_b, &b, sizeof(int), cudaMemcpyHostToDevice);



        //Launch Kernel
 AddIntsCUDA << <1, 1 >> >(d_a, d_b, d_c);

        //Copy Device Memory to Host Memory
 cudaMemcpy(&c, d_c, sizeof(int), cudaMemcpyDeviceToHost);

 printf("The answer is %d",c);


        //Free Device Memory
        cudaFree(d_a);
        cudaFree(d_b);
        cudaFree(d_c);
 return 0;
}



The answer is 14


In [ ]:
%%cu
#include<iostream>
#include<cuda.h>
#include<cuda_runtime.h>

using namespace std;

__device__ void print(int a, int b, int sum){
	printf("Printing sum inside DEVICE\n");
	printf("\n%d\t%d + %d = %d", threadIdx.x, a, b, sum);
}

__global__ void add(int *a, int *b, int* sum){
	*sum = *a + *b;
	print(*a, *b, *sum);
}

int main(){
	int *a, *b, *sum;
  //int a,b,sum;
	cudaMallocManaged(&a, sizeof(int));
	cudaMallocManaged(&b, sizeof(int));
	cudaMallocManaged(&sum , sizeof(int));
	cout<<"Enter A: ";
  cin>>*a;
	cout<<"Enter B: ";
  cin>>*b;
	add<<<1,10>>>(a,b,sum);
	cudaDeviceSynchronize();
	cout<<"\nPrinting sum in HOST: Sum is "<<*sum<<endl;
	return 0;
}


Enter A: Enter B: Printing sum inside DEVICE
Printing sum inside DEVICE
Printing sum inside DEVICE
Printing sum inside DEVICE
Printing sum inside DEVICE
Printing sum inside DEVICE
Printing sum inside DEVICE
Printing sum inside DEVICE
Printing sum inside DEVICE
Printing sum inside DEVICE

0	0 + 0 = 0
1	0 + 0 = 0
2	0 + 0 = 0
3	0 + 0 = 0
4	0 + 0 = 0
5	0 + 0 = 0
6	0 + 0 = 0
7	0 + 0 = 0
8	0 + 0 = 0
9	0 + 0 = 0
Printing sum in HOST: Sum is 0



In [ ]:
%%cu
#include<stdio.h>
#include<cuda.h>
 __global__ void cuda_hello()
 {
    printf("Hello World from my GPU :)");
 }
int main()
{
    cuda_hello<<<4,2>>>();
    cudaDeviceSynchronize();
    return 0;
}


Hello World from my GPU :)Hello World from my GPU :)Hello World from my GPU :)Hello World from my GPU :)Hello World from my GPU :)Hello World from my GPU :)Hello World from my GPU :)Hello World from my GPU :)


In [ ]:
#kernel define
## Kernel - Adding two matrices MatA and MatB
%%cu
#include<stdio.h>
#include<cuda.h>
__global__ void MatAdd(float MatA[N][N], float MatB[N][N],
float MatC[N][N])
{
    int i = blockIdx.x * blockDim.x + threadIdx.x;
    int j = blockIdx.y * blockDim.y + threadIdx.y;
    if (i < N && j < N)
        MatC[i][j] = MatA[i][j] + MatB[i][j];
}

int main()
{

    // Matrix addition kernel launch from host code
    dim3 threadsPerBlock(16, 16);
    dim3 numBlocks((N + threadsPerBlock.x -1) / threadsPerBlock.x, (N+threadsPerBlock.y -1) / threadsPerBlock.y);
    MatAdd<<<numBlocks, threadsPerBlock>>>(MatA, MatB, MatC);

}

/tmp/tmp1k7sl4ca/12b2de8e-6d11-41b9-9eda-5f88f04d80ee.cu(3): error: identifier "N" is undefined

/tmp/tmp1k7sl4ca/12b2de8e-6d11-41b9-9eda-5f88f04d80ee.cu(17): error: identifier "N" is undefined

/tmp/tmp1k7sl4ca/12b2de8e-6d11-41b9-9eda-5f88f04d80ee.cu(18): error: identifier "MatA" is undefined

/tmp/tmp1k7sl4ca/12b2de8e-6d11-41b9-9eda-5f88f04d80ee.cu(18): error: identifier "MatB" is undefined

/tmp/tmp1k7sl4ca/12b2de8e-6d11-41b9-9eda-5f88f04d80ee.cu(18): error: identifier "MatC" is undefined

5 errors detected in the compilation of "/tmp/tmp1k7sl4ca/12b2de8e-6d11-41b9-9eda-5f88f04d80ee.cu".



In [ ]:
%%cu
#include <stdio.h>
#include <stdlib.h>
#include<cuda.h>
#define N 2

__global__ void MatAdd(int A[][N], int B[][N], int C[][N]){
           int i = threadIdx.x;
           int j = threadIdx.y;

           C[i][j] = A[i][j] + B[i][j];
       }


int main(){

int A[N][N] = {{1,2},{3,4}};
int B[N][N] = {{5,6},{7,8}};
int C[N][N] = {{0,0},{0,0}};

int (*pA)[N], (*pB)[N], (*pC)[N];

cudaMalloc((void**)&pA, (N*N)*sizeof(int));//pA allocated on GPU
cudaMalloc((void**)&pB, (N*N)*sizeof(int));
cudaMalloc((void**)&pC, (N*N)*sizeof(int));

cudaMemcpy(pA, A, (N*N)*sizeof(int), cudaMemcpyHostToDevice);//CPU TO GPU COPIED
cudaMemcpy(pB, B, (N*N)*sizeof(int), cudaMemcpyHostToDevice);
cudaMemcpy(pC, C, (N*N)*sizeof(int), cudaMemcpyHostToDevice);

int numBlocks = 1;
dim3 threadsPerBlock(N,N);
MatAdd<<<numBlocks,threadsPerBlock>>>(pA,pB,pC);

cudaMemcpy(C, pC, (N*N)*sizeof(int), cudaMemcpyDeviceToHost);//GPU TO CPU COPIED

int i, j; printf("C = \n");
for(i=0;i<N;i++){
    for(j=0;j<N;j++){
        printf("%d ", C[i][j]);
    }
    printf("\n");
}

cudaFree(pA);
cudaFree(pB);
cudaFree(pC);
printf("\n");

return 0;
}

C = 
6 8 
10 12 




MATRIX ADDITION CUDA

In [ ]:
%%cu
#include<iostream>
#include<cuda.h>
#include<cuda_runtime.h>

#define N 3

using namespace std;

__global__ void matrixAdd(int (*a)[N], int (*b)[N], int (*c)[N]){

	int i = blockIdx.x;
	int j = threadIdx.x;
	c[i][j] = a[i][j] + b[i][j];

	printf("\nblockIdx.x: %d\ttheradIdx.x: %d\tthreadIdx.y: %d",blockIdx.x,threadIdx.x,threadIdx.y);
}

int main(){

	int a[N][N] = {{1,2,3},{4,5,6},{7,8,9}};
	int b[N][N] = {{1,2,3},{4,5,6},{7,8,9}};

	int size = N * N * sizeof(int);

	int c[N][N];

	int (*dev_a)[N], (*dev_b)[N], (*dev_c)[N];

	cudaMalloc(&dev_a, size);
	cudaMalloc(&dev_b, size);
	cudaMalloc(&dev_c, size);

	cudaMemcpy(dev_a, a, size, cudaMemcpyHostToDevice);
	cudaMemcpy(dev_b, b, size, cudaMemcpyHostToDevice);
	cudaMemcpy(dev_c, c, size, cudaMemcpyHostToDevice);

	dim3 TPB(N,N);
	matrixAdd<<<1,TPB>>>(dev_a, dev_b, dev_c);

	matrixAdd<<<3,3>>>(dev_a, dev_b, dev_c);

	cudaMemcpy(a, dev_a, size, cudaMemcpyDeviceToHost);
	cudaMemcpy(b, dev_b, size, cudaMemcpyDeviceToHost);
	cudaMemcpy(c, dev_c, size, cudaMemcpyDeviceToHost);

	cudaDeviceSynchronize();

	cout<<endl;
	for(int i=0; i<N; i++){
		for(int j=0; j<N; j++){
			cout<<c[i][j]<<"\t";
		}
		cout<<endl;
	}


	cudaFree(dev_a);
	cudaFree(dev_b);
	cudaFree(dev_c);

	return 0;
}


blockIdx.x: 0	theradIdx.x: 0	threadIdx.y: 0
blockIdx.x: 0	theradIdx.x: 1	threadIdx.y: 0
blockIdx.x: 0	theradIdx.x: 2	threadIdx.y: 0
blockIdx.x: 0	theradIdx.x: 0	threadIdx.y: 1
blockIdx.x: 0	theradIdx.x: 1	threadIdx.y: 1
blockIdx.x: 0	theradIdx.x: 2	threadIdx.y: 1
blockIdx.x: 0	theradIdx.x: 0	threadIdx.y: 2
blockIdx.x: 0	theradIdx.x: 1	threadIdx.y: 2
blockIdx.x: 0	theradIdx.x: 2	threadIdx.y: 2
blockIdx.x: 0	theradIdx.x: 0	threadIdx.y: 0
blockIdx.x: 0	theradIdx.x: 1	threadIdx.y: 0
blockIdx.x: 0	theradIdx.x: 2	threadIdx.y: 0
blockIdx.x: 2	theradIdx.x: 0	threadIdx.y: 0
blockIdx.x: 2	theradIdx.x: 1	threadIdx.y: 0
blockIdx.x: 2	theradIdx.x: 2	threadIdx.y: 0
blockIdx.x: 1	theradIdx.x: 0	threadIdx.y: 0
blockIdx.x: 1	theradIdx.x: 1	threadIdx.y: 0
blockIdx.x: 1	theradIdx.x: 2	threadIdx.y: 0
2	4	6	
8	10	12	
14	16	18	



In [ ]:
!lscpu | grep 'Number of threads/core:'

In [ ]:
! add-apt-repository ppa:graphics-drivers/ppa
! apt update
! apt install nvidia-384 nvidia-384-dev


 Fresh drivers from upstream, currently shipping Nvidia.

## Current Status

Current long-lived branch release: `nvidia-430` (430.40)
Dropped support for Fermi series (https://nvidia.custhelp.com/app/answers/detail/a_id/4656)

Old long-lived branch release: `nvidia-390` (390.129)

For GF1xx GPUs use `nvidia-390` (390.129)
For G8x, G9x and GT2xx GPUs use `nvidia-340` (340.107)
For NV4x and G7x GPUs use `nvidia-304` (304.137) End-Of-Life!

Support timeframes for Unix legacy GPU releases:
https://nvidia.custhelp.com/app/answers/detail/a_id/3142

## What we're working on right now:

- Normal driver updates
- Help Wanted: Mesa Updates for Intel/AMD users, ping us if you want to help do this work, we're shorthanded.

## WARNINGS:

This PPA is currently in testing, you should be experienced with packaging before you dive in here:

Volunteers welcome!

### How you can help:

## Install PTS and benchmark your gear:

    sudo apt-get install phoronix-test-suite

Run the benchmark:

    phoronix-

In [ ]:
!apt-get install cuda


In [ ]:
!nvcc --version

In [ ]:
# install cuda 10.0
!apt-get update;
!wget https://developer.nvidia.com/compute/cuda/10.0/Prod/local_installers/cuda-repo-ubuntu1604-10-0-local-10.0.130-410.48_1.0-1_amd64 -O cuda-repo-ubuntu1604-10-0-local-10.0.130-410.48_1.0-1_amd64.deb
!dpkg -i cuda-repo-ubuntu1604-10-0-local-10.0.130-410.48_1.0-1_amd64.deb
!apt-key add /var/cuda-repo-10-0-local/7fa2af80.pub
!apt-get update
!apt-get -y install gcc-7 g++-7
!apt-get -y install cuda

!export PATH=/usr/local/cuda/bin${PATH:+:${PATH}}
!export LD_LIBRARY_PATH=/usr/local/cuda/lib64\${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}

# check if installed successfully
!/usr/local/cuda/bin/nvcc --version

# install python-nvcc plugin
!pip install git+git://github.com/andreinechaev/nvcc4jupyter.git
%load_ext nvcc_plugin




AN EXAMPLE int10x10.csv file

In [ ]:
from google.colab import files
uploaded=files.upload()

Saving int10x10.csv to int10x10.csv


READING CSV FILE USING CUDA C

In [ ]:
%%cu
#include<cuda.h>
#include<cuda_runtime.h>
#include<stdio.h>
#include<string.h>
#include<stdbool.h>

#define MAXCHAR 1000
//include gpu functionality
int main(){

    FILE *fp;
    char row[MAXCHAR];

    fp = fopen("/content/int10x10.csv","r");

    while (feof(fp) != true)
    {
        fgets(row, MAXCHAR, fp);
        printf("Row: %s", row);
    }


    return 0;
}



Row: 82; 41; 37; 94; 28; 30; 60; 91; 75; 91
Row: 64; 40; 16; 64; 48; 11; 53; 28; 74; 21
Row: 67; 49; 34; 82; 45; 40; 72; 86; 41; 89
Row: 69; 81; 37; 90; 34; 56; 23; 53; 35; 91
Row: 55; 81; 91; 16; 11; 59; 62; 19; 24; 13
Row: 61; 49; 18; 24; 18; 57; 57; 77; 23; 68
Row: 97; 19; 26; 50; 26; 65; 19; 67; 18; 28
Row: 27; 98; 49; 40; 53; 68; 20; 61; 61; 65
Row: 24; 65; 93; 19; 96; 65; 88; 55; 41; 13
Row: 81; 60; 71; 66; 47; 26; 24; 99; 47; 52
Row: 81; 60; 71; 66; 47; 26; 24; 99; 47; 52



In [ ]:
from numba import jit, cuda
import numpy as np
# to measure exec time
from timeit import default_timer as timer

# normal function to run on cpu
def func(a):
	for i in range(10000000):
		a[i]+= 1

# function optimized to run on gpu
@jit(target_backend='cuda')
def func2(a):
	for i in range(10000000):
		a[i]+= 1
if __name__=="__main__":
	n = 10000000
	a = np.ones(n, dtype = np.float64)

	start = timer()
	func(a)
	print("without GPU:", timer()-start)

	start = timer()
	func2(a)
	print("with GPU:", timer()-start)


In [ ]:
%%cu
#include<cuda.h>
#include<cuda_runtime.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

int main()
{
    char str[50];
    FILE* ptr;
    ptr = fopen("/content/int10x10.csv", "r");
 if (!fp)
        printf("Can't open file\n");

 else
        char buffer[1024];

        int row = 0;
        int column = 0;

        while (fgets(buffer,1024, fp))
        {
            column ++;
            row++;
         printf(fp);
            printf("\n");
         }

		// Close the file
		fclose(fp);
	return 0;
}



/tmp/tmprl4a95w6/30de68ad-1ad3-4502-8173-232f3f41305a.cu(12): error: identifier "fp" is undefined

/tmp/tmprl4a95w6/30de68ad-1ad3-4502-8173-232f3f41305a.cu(16): warning #177-D: variable "buffer" was declared but never referenced

/tmp/tmprl4a95w6/30de68ad-1ad3-4502-8173-232f3f41305a.cu(21): error: identifier "buffer" is undefined

/tmp/tmprl4a95w6/30de68ad-1ad3-4502-8173-232f3f41305a.cu(9): warning #177-D: variable "str" was declared but never referenced

/tmp/tmprl4a95w6/30de68ad-1ad3-4502-8173-232f3f41305a.cu(10): warning #550-D: variable "ptr" was set but never used

2 errors detected in the compilation of "/tmp/tmprl4a95w6/30de68ad-1ad3-4502-8173-232f3f41305a.cu".



In [ ]:
// C program for the above approach
#include <conio.h>
#include <stdio.h>
#include <string.h>

// Driver Code
int main()
{
	// Substitute the full file path
	// for the string file_path
	FILE* fp = fopen("file_path", "r");

	if (!fp)
		printf("Can't open file\n");

	else {
		// Here we have taken size of
		// array 1024 you can modify it
		char buffer[1024];

		int row = 0;
		int column = 0;

		while (fgets(buffer,
					1024, fp)) {
			column = 0;
			row++;


			printf("\n");
		}

		// Close the file
		fclose(fp);
	}
	return 0;
}


In [ ]:
// C program for the above approach
#include <conio.h>
#include <stdio.h>
#include <string.h>

// Driver Code
int main()
{
	// Substitute the full file path
	// for the string file_path
	FILE* fp = fopen("file_path", "r");

	if (!fp)
		printf("Can't open file\n");

	else {
		// Here we have taken size of
		// array 1024 you can modify it
		char buffer[1024];

		int row = 0;
		int column = 0;

		while (fgets(buffer,
					1024, fp)) {
			column = 0;
			row++;

			// To avoid printing of column
			// names in file can be changed
			// according to need
			if (row == 1)
				continue;

			// Splitting the data
			char* value = strtok(buffer, ", ");

			while (value) {
				// Column 1
				if (column == 0) {
					printf("Name :");
				}

				// Column 2
				if (column == 1) {
					printf("\tAccount No. :");
				}

				// Column 3
				if (column == 2) {
					printf("\tAmount :");
				}

				printf("%s", value);
				value = strtok(NULL, ", ");
				column++;
			}

			printf("\n");
		}

		// Close the file
		fclose(fp);
	}
	return 0;
}


In [ ]:
%%cu
#include<cuda.h>
#include<cuda_runtime.h>
#include <stdio.h>
#include <stdlib.h>
#include <algorithm>


void dot(int numElements, const float3* a, const float3* b, float* c)
{
    for (int i = 0; i < numElements; i++)
    {
        c[i] = a[i].x*b[i].x + a[i].y*b[i].y + a[i].z*b[i].z;
    }
}

int main()
{
    int numElements = 10000;

    float3* a = (float3*)calloc(numElements, sizeof(float3));
    float3* b = (float3*)calloc(numElements, sizeof(float3));
    float* c = (float*)calloc(numElements, sizeof(float));

    srand(1214134);
    for (int i = 0; i < numElements; i++)
    {
        a[i].x = float(rand())/float(RAND_MAX + 1.0);
        a[i].y = float(rand())/float(RAND_MAX + 1.0);
        a[i].z = float(rand())/float(RAND_MAX + 1.0);

        b[i].x = float(rand())/float(RAND_MAX + 1.0);
        b[i].y = float(rand())/float(RAND_MAX + 1.0);
        b[i].z = float(rand())/float(RAND_MAX + 1.0);
    }



    for (int i = 0; i < std::min(10, numElements); i++)
    {
        printf("%f*%f + %f*%f + %f*%f = %f\n", a[i].x, b[i].x, a[i].y, b[i].y, a[i].z, b[i].z, c[i]);
    }
    printf("...\n");

    free(a);
    free(b);
    free(c);



    return 0;
}

0.471312*0.654028 + 0.755417*0.130242 + 0.113776*0.698572 = 0.000000
0.223085*0.033497 + 0.130136*0.779934 + 0.959257*0.993333 = 0.000000
0.116120*0.271912 + 0.603113*0.516974 + 0.397982*0.064489 = 0.000000
0.088946*0.662415 + 0.665688*0.513010 + 0.850821*0.378750 = 0.000000
0.115836*0.972258 + 0.080736*0.112544 + 0.039045*0.836265 = 0.000000
0.560405*0.674181 + 0.583856*0.237884 + 0.591683*0.721925 = 0.000000
0.372753*0.332010 + 0.460968*0.494466 + 0.852060*0.631994 = 0.000000
0.325343*0.723325 + 0.610586*0.882498 + 0.235108*0.752081 = 0.000000
0.787814*0.638635 + 0.971445*0.633860 + 0.417769*0.930779 = 0.000000
0.017385*0.056431 + 0.749696*0.721955 + 0.011515*0.124059 = 0.000000
...



In [ ]:
!git clone https://github.com/ENCCS/OpenACC-CUDA-beginners.git

Cloning into 'OpenACC-CUDA-beginners'...
remote: Enumerating objects: 1380, done.
remote: Counting objects: 100% (50/50), done.
remote: Compressing objects: 100% (23/23), done.
remote: Total 1380 (delta 30), reused 27 (delta 27), pack-reused 1330
Receiving objects: 100% (1380/1380), 14.09 MiB | 29.87 MiB/s, done.
Resolving deltas: 100% (677/677), done.


In [ ]:
%load_ext nvcc_plugin

The nvcc_plugin extension is already loaded. To reload it, use:
  %reload_ext nvcc_plugin


In [ ]:
%%cu
#include <stdio.h>
#ifdef _OPENACC
#include <openacc.h>
#endif

#define NX 102400

int main(void)
{
    double vecA[NX], vecB[NX], vecC[NX];
    double sum;
    int i;

    /* Initialization of the vectors */
    for (i = 0; i < NX; i++) {
        vecA[i] = 1.0 / ((double) (NX - i));
        vecB[i] = vecA[i] * vecA[i];
    }

    /*
     * Implement vector addition on device with OpenACC
     * vecC = vecA + vecB
     */
    for (i = 0; i < NX; i++) {
       vecC[i] = vecA[i] + vecB[i];
    }

    sum = 0.0;
    /* Compute the check value */
    for (i = 0; i < NX; i++) {
        sum += vecC[i];
    }
    printf("Reduction sum: %18.16f\n", sum);

    return 0;
}

Reduction sum: 13.7587868405645448



In [ ]:
//matrix addition
%%cu
#include<iostream>
#include<cuda.h>
#include<cuda_runtime.h>

#define N 3

using namespace std;

__global__ void matrixAdd(int (*a)[N], int (*b)[N], int (*c)[N]){

	int i = blockIdx.x;
	int j = threadIdx.x;
	c[i][j] = a[i][j] + b[i][j];

	printf("\nblockIdx.x: %d\ttheradIdx.x: %d\tthreadIdx.y: %d",blockIdx.x,threadIdx.x,threadIdx.y);
}

int main(){

	int a[N][N] = {{1,2,3},{4,5,6},{7,8,9}};
	int b[N][N] = {{1,2,3},{4,5,6},{7,8,9}};

	int size = N * N * sizeof(int);

	int c[N][N];

	int (*dev_a)[N], (*dev_b)[N], (*dev_c)[N];

	cudaMalloc(&dev_a, size);
	cudaMalloc(&dev_b, size);
	cudaMalloc(&dev_c, size);

	cudaMemcpy(dev_a, a, size, cudaMemcpyHostToDevice);
	cudaMemcpy(dev_b, b, size, cudaMemcpyHostToDevice);
	cudaMemcpy(dev_c, c, size, cudaMemcpyHostToDevice);

	dim3 TPB(N,N);
	matrixAdd<<<1,TPB>>>(dev_a, dev_b, dev_c);

	matrixAdd<<<3,3>>>(dev_a, dev_b, dev_c);

	cudaMemcpy(a, dev_a, size, cudaMemcpyDeviceToHost);
	cudaMemcpy(b, dev_b, size, cudaMemcpyDeviceToHost);
	cudaMemcpy(c, dev_c, size, cudaMemcpyDeviceToHost);

	cudaDeviceSynchronize();

	cout<<endl;
	for(int i=0; i<N; i++){
		for(int j=0; j<N; j++){
			cout<<c[i][j]<<"\t";
		}
		cout<<endl;
	}


	cudaFree(dev_a);
	cudaFree(dev_b);
	cudaFree(dev_c);

	return 0;
}

MATRIX MULTIPLICATION

In [ ]:
%%cu
#include<openacc.h>
#include<stdio.h>

void matrix_mul(int n, float *A, float *B, float *C)
{
    #pragma acc parallel loop collapse(2)
    for (int i = 0; i < n; ++i) {
        for (int j = 0; j < n; ++j) {
            float sum = 0.0;
            for (int k = 0; k < n; ++k) {
                sum += A[i * n + k] * B[k * n + j];
            }
            C[i * n + j] = sum;
        }
    }
}

int main()
{
    int n = 1024; // Matrix size
    float *A = (float *)malloc(n * n * sizeof(float));
    float *B = (float *)malloc(n * n * sizeof(float));
    float *C = (float *)malloc(n * n * sizeof(float));

    // Initialize matrices A and B with random values
    for (int i = 0; i < n * n; ++i) {
        A[i] = (float)rand() / RAND_MAX;
        B[i] = (float)rand() / RAND_MAX;
    }

    // Compute matrix multiplication using OpenACC
    #pragma acc data copyin(A[0:n*n], B[0:n*n]) copyout(C[0:n*n])
    {
        matrix_mul(n, A, B, C);
    }

    // Print result
    printf("Matrix C:\n");
    for (int i = 0; i < n; ++i) {
        for (int j = 0; j < n; ++j) {
            printf("%.2f ", C[i * n + j]);
        }
        printf("\n");
    }

    free(A);
    free(B);
    free(C);

    return 0;
}

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)




255.88 266.58 271.70 257.12 263.89 260.73 254.52 258.08 257.48 254.89 245.93 255.33 260.92 252.60 254.23 266.33 263.23 250.67 264.53 259.26 254.85 257.33 258.68 260.31 258.05 270.47 265.11 257.22 264.07 264.27 252.65 256.14 259.64 247.09 256.55 251.37 254.68 258.97 259.99 259.39 254.71 253.93 257.87 253.79 260.25 260.52 252.71 252.87 257.37 257.41 259.23 271.37 267.26 258.24 263.26 262.14 258.67 257.02 259.49 254.22 261.84 260.55 258.87 257.96 268.05 254.76 255.01 263.72 260.67 251.40 257.83 264.89 267.06 259.94 264.27 253.83 269.49 260.84 258.84 267.13 257.82 267.84 263.44 262.00 256.29 259.49 252.62 265.82 264.48 263.47 262.17 249.79 256.89 252.56 268.42 260.76 259.39 254.78 264.10 262.91 262.36 266.76 270.89 262.41 263.01 259.43 258.98 252.85 260.59 268.22 268.61 253.13 262.64 263.13 263.09 249.76 262.37 257.07 268.13 261.64 259.94 267.13 254.41 262.67 255.52 256.46 250.80 264.01 253.91 250.78 257.38 255.85 260.14 262.33 253.57 264.21 261.50 262.91 252.21 264.55 256.98 264.76 264.9